#include "DnsSensor.h"

static const GUID DNSClientProviderGuid =
{ 0x1C95126E, 0x7EEA, 0x49A9, {0xA3, 0xFE, 0xA3, 0x78, 0xB0, 0x3D, 0xDB, 0x4D } };

DnsSensor::DnsSensor() : WinETWSensor((LPWSTR) L"Microsoft-Windows-DNS-Client", DNSClientProviderGuid)
{

}

void DnsSensor::eventReceived(PEVENT_RECORD evt)
{
    wprintf(L"Received Event on DNS Sensor\n");
    wprintf(L"Generated By ProcessId: %u\n", evt->EventHeader.ProcessId);
    PBYTE value = NULL;
    if (getPropertyValue(evt, (LPWSTR)L"QueryName", &value))
    {
        wprintf(L"QueryName: %s\n", (LPWSTR) value);
        free(value);
    }

    if (getPropertyValue(evt, (LPWSTR)L"QueryType", &value))
    {
        wprintf(L"QueryType: %d\n", *(PBYTE) value);
        free(value);
    }
}

std::string DnsSensor::getInfo()
{
    return "";
}